FROM php:5.6-apache
RUN pecl install xdebug-2.5.5 && docker-php-ext-enable xdebug
RUN docker-php-ext-install mysql mysqli pdo # Moved to Dockerfile-base
RUN apt-get update && apt-get install -y graphviz mysql-client # Moved to Dockerfile-base
